sudo: false
language: node_js
node_js:
  - "5.1"
  - "4.1"
services:
  - mongodb
before_script:
  - npm install -g mocha #for npm test
  - npm install istanbul #for run-script cov
  - npm install grunt #for grunt coveralls
  - npm install grunt-coveralls #for grunt coveralls 
script:
  - sleep 15
  - npm test
  - npm run-script cov || true #it may fail after generating the lcov - ignore
  - grunt coveralls || true #it may fail in some cases - ignore
